name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: dependencies
        run: cd BTNav && yarn install
      - name: types
        run: cd BTNav && yarn tsc
      - name: linting
        run: cd BTNav && yarn eslint
